name: 'Setup Stackgen'
description: 'Sets up Stackgen CLI and configures it'

inputs:
  stackgen-token:
    description: 'Stackgen API Token'
    required: true
  stackgen-url:
    description: 'Stackgen API URL'
    default: 'https://cloud.stackgen.com/'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Brew install stackgen
      shell: bash
      run: brew install appcd-dev/stackgen/stackgen

    - name: Run Stackgen version
      shell: bash
      run: stackgen version

    - name: Stackgen Configure
      shell: bash
      env:
        STACKGEN_TOKEN: ${{ inputs.stackgen-token }}
        STACKGEN_URL: ${{ inputs.stackgen-url }}
      run: stackgen configure
