name: Setup Stackgen
on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      STACKGEN_TOKEN: ${{ secrets.STACKGEN_TOKEN }}
      STACKGEN_URL: "https://main.dev.stackgen.com/"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Brew install stackgen
        run: brew install appcd-dev/stackgen/stackgen

      - name: Run Stackgen version
        run: stackgen version

      - name: Stackgen Configure
        run: stackgen configure
