name: Stackgen Destroy
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      STACKGEN_URL: "https://main.dev.stackgen.com/"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Stackgen
        uses: ./.github/actions/setup-stackgen
        with:
          stackgen-token: ${{ secrets.STACKGEN_TOKEN }}
          stackgen-url: ${{ env.STACKGEN_URL }}

      - name: Run Stackgen destroy
        run: stackgen destroy --appstack-id fc214ec5-c911-417f-9a63-09cf04f59cf9 --var="region=us-east-2"
