name: Stackgen Provision
on:
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/setup-stackgen.yaml
    secrets:
      STACKGEN_TOKEN: ${{ secrets.STACKGEN_TOKEN }}

  provision:
    needs: setup
    runs-on: ubuntu-latest
    env:
      STACKGEN_TOKEN: ${{ secrets.STACKGEN_TOKEN }}
      STACKGEN_URL: "https://main.dev.stackgen.com/"
    steps:
      - name: Run Stackgen provision
        run: stackgen provision --appstack-id 9689f1af-3955-40b4-bd58-816a661bf3b1 --var="region=us-east-2"
