name: Stackgen Destroy
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      STACKGEN_URL: "https://main.dev.stackgen.com/"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Stackgen
        uses: ./.github/actions/setup-stackgen
        with:
          stackgen-token: ${{ secrets.STACKGEN_TOKEN }}
          stackgen-url: ${{ env.STACKGEN_URL }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get UUID for "simple-iac" appstack
        id: get-uuid
        run: |
          APPSTACK_UUID=$(stackgen list-appstacks | jq -r '.[] | select(.appstack_name == "simple-iac") | .uuid')
          echo "APPSTACK_UUID=$APPSTACK_UUID" >> $GITHUB_ENV

      - name: Run Stackgen destroy
        run: stackgen destroy --appstack-id ${{ env.APPSTACK_UUID }} --var="region=us-east-2"
